### ISSUE TITLE
Refinements to code of conduct

### ISSUE THREAD

**Issue by dvberkel** [ClojureNauts/code-of-conduct#1]
@pxlpnk @gregkare  I took the liberty to create a code of conduct for [ClojureNauts](https://github.com/ClojureNauts) because I think it is important that what ever ClojureNauts becomes, it should be inclusive, accepting and safe. I based the code of conduct on [confcodeofconduct.com](http://confcodeofconduct.com/) and adopted it to our needs. Still it probably could be improved. Could you review it?

**Comment by pxlpnk** [comment]
Looks good! (: Staff sounds funny in this context! :+1:

**Comment by dvberkel** [comment]
@pxlpnk I agree. Let's see if we can come up with an alternative to staff.

**Comment by dvberkel** [comment]
If there are no more refinements announced within a week from now, I am going to close this issue.

**Comment by pxlpnk** [comment]
It looks good from my side!
We also should start a pet project to get more into Clojure and learn!

**Comment by dvberkel** [comment]
:+1:

**Comment by dvberkel** [comment]
I am closing the issue because no refinements were announced.

If you have an suggestion for improvement, feel free to open it.
